# These are supported funding model platforms

github: diddledani
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: diddledani
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
liberapay: diddledani
custom: # Replace with a single URL
