name: $(Date:yyyyMMdd).$(Rev:.r)

jobs:
- template: .azure-pipelines/phpunit.yml
  parameters:
    phpvers:
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
    - '7.3'
    multisite:
    - false
    - true
    wpvers:
    - '4.6'
    - '4.7'
    - '4.8'
    - '4.9'
    - '5.0'
    - '5.1'
    - '5.2'
    - latest
    - nightly

- job: PHPCS
  displayName: PHP Code Sniffer
  pool:
    vmImage: 'ubuntu-16.04'
  container: php73
  steps:
  - bash: composer global require wp-coding-standards/wpcs
  - bash: $HOME/.composer/vendor/bin/phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
