include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - project: a-z-listing/ci-config
    file: /build-and-test.yml
  - project: a-z-listing/ci-config
    file: /release-WordPress.org.yml

stages:
  - build
  - test
  - release
