include:
  - template: Code-Quality.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - local: .gitlab-ci/_prereqs.yml
  - local: .gitlab-ci/build.yml
  - local: .gitlab-ci/test-matrix.yml

stages:
  - build
  - test
  # - release

# .release:
#   stage: release
#   only:
#     - tags
