include:
  - template: Code-Quality.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - project: a-z-listing/ci-config
    file: /build-and-test.yml
  - project: a-z-listing/ci-config
    file: /release-WordPress.org.yml

code_quality:
  services:
    - name: docker:stable-dind
      command: [--storage-driver, aufs]


stages:
  - build
  - test
  - release
