.phpunit:
  stage: test
  needs: [build]
  extends: .base
  services:
    - mysql:5.6
  script:
    - bash bin/install-wp-tests.sh "${MYSQL_DATABASE:-wordpress}" root "$MYSQL_ROOT_PASSWORD" mysql $WP_VERSION true
    - ./tools/phpunit --log-junit phpunit-results.xml --coverage-text
  artifacts:
    reports:
      junit: phpunit-results.xml

.phpunit-multisite:
  extends: .phpunit
  script:
    - bash bin/install-wp-tests.sh "${MYSQL_DATABASE:-wordpress}" root "$MYSQL_ROOT_PASSWORD" mysql $WP_VERSION true
    - ./tools/phpunit -c phpunit-multisite.xml --log-junit phpunit-results.xml --coverage-text
