build:
  stage: build
  image: php:7.4
  extends: .base
  script:
    - phive install humbug/php-scoper@0.11.4 --force-accept-unsigned
    ## Uncomment if dev dependencies are needed
    # - composer install --prefer-dist --no-interaction --no-progress --no-suggest
    # - rm -rf vendor
    - composer install --no-dev --optimize-autoloader --prefer-dist --no-interaction --no-progress --no-suggest
    - ./tools/php-scoper add-prefix --no-interaction
    - |
      [ -s "$HOME/.nvm/nvm.sh" ] && \. "$HOME/.nvm/nvm.sh";
      $HOME/.yarn/bin/yarn install --non-interactive --no-progress
      $HOME/.yarn/bin/yarn build
      rm -rf node_modules
      $HOME/.yarn/bin/yarn install --production --no-bin-links --non-interactive --no-progress
  artifacts:
    name: "$CI_JOB_NAME"
    expire_in: 30 days
    paths:
      - vendor/
      - build/
      - languages/
      - css/
