parameters:
  phpvers: []
  wpvers: []
  multisites: [0, 1]

jobs:
- ${{ each phpver in parameters.phpvers }}:
  - ${{ each wpver in parameters.wpvers }}:
    - ${{ each doMultisite in parameters.multisites }}:
      - ${{ if eq(doMultisite, 0) }}:
          job: PHPUnit; PHP ${{ phpver }}; WP ${{ wpver }}
        ${{ if eq(doMultisite, 1) }}:
          job: PHPUnit; PHP ${{ phpver }}; WP ${{ wpver }} (multisite)
        pool:
          vmImage: 'ubuntu-16.04'
        container: diddledan/gitlab-php-runner:${{ phpver }}
        variables:
          WP_VERSION: ${{ wpver }}
          WP_MULTISITE: ${{ doMultisite }}
        services:
          mysql: mysql
        steps:
        - bash: bin/install-wp-tests.sh wordpress_test root '' "${AGENT_SERVICES_MYSQL_PORTS_3306}" $WP_VERSION
        - bash: composer global require "phpunit/phpunit=4.8.*|5.7.*"
        - bash: phpunit --log-junit phpunit.xml
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: JUnit
            testResultsFiles: 'phpunit.xml'
            failTaskOnFailedTests: true
