parameters:
  phpvers: []
  wpvers: []
  multisites:
  - name: 'normal'
    value: 0
  - name: 'multisite'
    value: 1

jobs:
- ${{ each phpver in parameters.phpvers }}:
  - ${{ each wpver in parameters.wpvers }}:
    - ${{ each doMultisite in parameters.multisites }}:
      - job: PHPUnit_${{ phpver.name }}_${{ wpver.name }}_${{ doMultisite.name }}
        displayName: PHPUnit PHP-${{ phpver.value }} WordPress-${{ wpver.value }} (${{ doMultisite.name }})
        pool:
          vmImage: 'ubuntu-16.04'
        container: bowlhat/gitlab-php-runner:${{ phpver.value }}
        variables:
          WP_VERSION: ${{ wpver.value }}
          WP_MULTISITE: ${{ doMultisite.value }}
        services:
          mysql: mysql
        steps:
        - bash: |
            sudo apt-get -yqq update
            sudo env DEBIAN_FRONTEND=noninteractive apt-get -yqqf install zip unzip subversion mariadb-client libmariadb-dev --fix-missing
          displayName: Install dependencies from APT
        - bash: bin/install-wp-tests.sh wordpress_test root '' "${AGENT_SERVICES_MYSQL_PORTS_3306}" $WP_VERSION
          displayName: Install WordPress tests
        - bash: composer global require "phpunit/phpunit=4.8.*|5.7.*"
          displayName: Install PHPUnit
        - bash: phpunit --log-junit phpunit.xml
          displayName: Run test suite
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: JUnit
            testResultsFiles: 'phpunit.xml'
            failTaskOnFailedTests: true
          displayName: Save test results
