name: "🚀 RELEASE: asset/readme on WordPress.org"

on:
  push:
    branches:
    - master
jobs:
  master:
    name: Push to master
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bowlhat'
    steps:
    - uses: actions/checkout@v2

    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@1.4.1
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: a-z-listing
