name: "🚀 RELEASE: To WordPress.org"
on:
  release:
    types: [ published ]
jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: pcov
          extensions: mbstring, intl
          tools: composer
      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          npm install
      - name: Run build
        run: |
          npm run build
      - name: Trim to production dependencies
        run: |
          npm prune --production
      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: a-z-listing
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.deploy.outputs.zip-path }}
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip

      - name: Update website docs
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SITE_DIRECTORY: ${{ secrets.SITE_DIRECTORY }}
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          mv wp-cli.phar /tmp/wp
          chmod +x /tmp/wp

          mkdir -p $HOME/.ssh
          cp known_hosts $HOME/.ssh/
          touch $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_rsa

          POSTS_TO_DELETE=$(/tmp/wp --ssh=$SSH_USERNAME@$SSH_HOST:$SITE_DIRECTORY post list \
            --post_type=wp-parser-function,wp-parser-method,wp-parser-class,wp-parser-hook \
            --format=ids)
          /tmp/wp --ssh=$SSH_USERNAME@$SSH_HOST:$SITE_DIRECTORY post delete $POSTS_TO_DELETE

          for tax in wp-parser-source-file wp-parser-source-file wp-parser-since wp-parser-since; do
            TERMS_TO_DELETE=$(/tmp/wp --ssh=$SSH_USERNAME@$SSH_HOST:$SITE_DIRECTORY term list $tax --format=ids)
            /tmp/wp --ssh=$SSH_USERNAME@$SSH_HOST:$SITE_DIRECTORY term delete $tax $TERMS_TO_DELETE
          done

          /tmp/wp --ssh=$SSH_USERNAME@$SSH_HOST:$SITE_DIRECTORY parser create wp-content/plugins/a-z-listing --user=diddledani
