name: "🚀 RELEASE: To WordPress.org"
on:
  release:
    types: [ published ]
jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mbstring, intl
          tools: composer
      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          npm install
      - name: Run build
        run: |
          npm run build
      - name: Trim to production dependencies
        run: |
          npm prune --production
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: a-z-listing
      - name: Create Artifact
        run: |
          mkdir plugin-build
          composer archive -vvv --format=zip --file="plugin-build/a-z-listing"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: a-z-listing
          path: plugin-build/a-z-listing.zip
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: plugin-build/a-z-listing.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}