name: Run PHPCS on pull requests

on:
- push
- pull_request

jobs:
  stale:

    runs-on: ubuntu-latest
    
    steps:
    - uses: rtCamp/action-phpcs-code-review@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        args: "WordPress,WordPress-Core,WordPress-Docs"
