name: Run PHPCS on pull requests

on:
- push
- pull_request

jobs:
  stale:

    runs-on: ubuntu-latest
    
    steps:
    - uses: bowlhat/action-phpcs-code-review@master
      with:
        gh_bot_token: ${{ secrets.GITHUB_TOKEN }}
        args: "WordPress,WordPress-Core,WordPress-Docs"
