name: Run PHPCS on pull requests

on:
- push
- pull_request

jobs:
  phpcs:

    runs-on: ubuntu-latest
    
    steps:
    - uses: rtCamp/action-phpcs-code-review@master
      env:
        GH_BOT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: "WordPress,WordPress-Core,WordPress-Docs"
