name: Run PHPCS on pull requests

on:
- pull_request

jobs:
  phpcs:
    name: phpcs
    strategy:
      matrix:
        php: ['7.4']
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: iconv intl xml soap opcache pdo pdo_mysql mysqli mbstring gd
        ini-values: phar.readonly=0

    - uses: actions/checkout@v2

    - name: Run composer install
      run: |
        composer install

    - name: Run PHPCS Coding Standards
      run: ./vendor/bin/phpcs $GITHUB_WORKSPACE
