name: Run PHPUnit on pull requests

on:
- pull_request

jobs:
  build:
    name: Build
    strategy:
      matrix:
        node: ['10.16.3']
        php: ['7.4']
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: iconv, intl, soap, mbstring, mysql, mysqli, gd
        ini-values: phar.readonly=0
        tools: composer

    - name: Get composer cache directory
      id: composercache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache composer dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composercache.outputs.dir }}
        key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-cache-

    - uses: actions/checkout@v2

    - name: Install php-scoper
      run: |
        composer global config minimum-stability dev
        composer global require humbug/php-scoper --prefer-dist --no-interaction --no-progress

    - name: Install composer dependencies
      run: composer install --prefer-dist --no-interaction --no-progress

    - name: Run php-scoper
      run: php-scoper add-prefix

    - name: Remove composer dev dependencies
      run: composer update --no-dev --optimize-autoloader --prefer-dist --no-interaction --no-progress

    - name: Run npm install
      run: |
        if [ -s "$HOME/.nvm/nvm.sh" ]; then \. "$HOME/.nvm/nvm.sh"; fi
        npm install

    - name: Run npm build
      run: |
        if [ -s "$HOME/.nvm/nvm.sh" ]; then \. "$HOME/.nvm/nvm.sh"; fi
        npm run build

    - name: Trim to production node_modules
      run: |
        rm -rf node_modules
        if [ -s "$HOME/.nvm/nvm.sh" ]; then \. "$HOME/.nvm/nvm.sh"; fi
        npm install --production --no-bin-links

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build/**/*

    - name: Upload composer vendor dir
      uses: actions/upload-artifact@v2
      with:
        name: vendor
        path: vendor/**/*

    - name: Upload languages
      uses: actions/upload-artifact@v2
      with:
        name: languages
        path: languages/**/*

    - name: Upload styles
      uses: actions/upload-artifact@v2
      with:
        name: css
        path: css/**/*

  test:
    name: Test
    needs: build
    strategy:
      matrix:
        multisite: ['0', '1']
        php:
        - '7.0'
        - '7.1'
        - '7.2'
        - '7.3'
        - '7.4'
        # - '8.0'
        wordpress:
        - '5.0'
        - '5.1'
        - '5.2'
        - '5.3'
        - '5.4'
        - '5.5'
        - '5.6'
        - latest
        - trunk
        exclude:
        - wordpress: '5.0'
          php: '7.4'
          multisite: '0'
        - wordpress: '5.1'
          php: '7.4'
          multisite: '0'
        - wordpress: '5.2'
          php: '7.4'
          multisite: '0'
        - wordpress: '5.0'
          php: '7.4'
          multisite: '1'
        - wordpress: '5.1'
          php: '7.4'
          multisite: '1'
        - wordpress: '5.2'
          php: '7.4'
          multisite: '1'
        # - wordpress: '5.0'
        #   php: '8.0'
        #   multisite: '0'
        # - wordpress: '5.1'
        #   php: '8.0'
        #   multisite: '0'
        # - wordpress: '5.2'
        #   php: '8.0'
        #   multisite: '0'
        # - wordpress: '5.3'
        #   php: '8.0'
        #   multisite: '0'
        # - wordpress: '5.4'
        #   php: '8.0'
        #   multisite: '0'
        # - wordpress: '5.5'
        #   php: '8.0'
        #   multisite: '0'
        # - wordpress: '5.0'
        #   php: '8.0'
        #   multisite: '1'
        # - wordpress: '5.1'
        #   php: '8.0'
        #   multisite: '1'
        # - wordpress: '5.2'
        #   php: '8.0'
        #   multisite: '1'
        # - wordpress: '5.3'
        #   php: '8.0'
        #   multisite: '1'
        # - wordpress: '5.4'
        #   php: '8.0'
        #   multisite: '1'
        # - wordpress: '5.5'
        #   php: '8.0'
        #   multisite: '1'
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306/tcp
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: iconv, intl, soap, mbstring, mysql, mysqli, gd
        ini-values: phar.readonly=0
        tools: phpunit:6.5.5

    - uses: actions/checkout@v2

    - name: Download build files
      uses: actions/download-artifact@v2

    - name: Install WordPress Test Suite
      run: ./bin/install-wp-tests.sh wordpress_test root root 127.0.0.1:${{ job.services.mysql.ports[3306] }} ${{ matrix.wordpress }}

    - name: Run phpunit
      run: |
        if [ ${{ matrix.multisite }} -eq 1 ]; then
          phpunit --verbose -c phpunit-multisite.xml
        else
          phpunit --verbose -c phpunit.xml.dist
        fi

  coverage:
    name: coverage
    needs:
    - build
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306/tcp
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: iconv, intl, soap, mbstring, mysql, mysqli, gd
        ini-values: phar.readonly=0
        tools: phpunit:6.5.5

    - uses: actions/checkout@v2

    - name: Download build files
      uses: actions/download-artifact@v2

    - name: Install WordPress Test Suite
      run: ./bin/install-wp-tests.sh wordpress_test root root 127.0.0.1:${{ job.services.mysql.ports[3306] }} latest

    - uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: 6d7dda243546c14b3eb3897386f7f8a7807cbe0984a8d51ac9c1cf37a07a4e55
      with:
        coverageCommand: phpunit --verbose -c phpunit.xml.dist --coverage-clover clover.xml
        coverateLocations: ${{github.workspace}}/clover.xml:clover
