name: Run PHPUnit on pull requests

on:
- push
- pull_request

jobs:
  build:
    name: Build
    strategy:
      matrix:
        node: ['10.16.3']
        php: ['7.4']
    runs-on: ubuntu-latest
    container:
      image: php:${{ matrix.php }}
      volumes:
      - $GITHUB_WORKSPACE:/var/www/html
    steps:
    - name: Set up container
      run: |
        echo "Install base packages"
        apt-get update
        apt-get install -y build-essential \
        libssl-dev \
        gnupg \
        libfreetype6-dev \
        libicu-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libonig-dev \
        libxml2-dev \
        vim \
        wget \
        unzip \
        git \
        subversion \
        default-mysql-client

        echo "Install composer"
        curl -sS -L https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer

        echo "Install PHP extensions"
        docker-php-ext-install -j$(nproc) iconv intl xml soap opcache pdo pdo_mysql mysqli mbstring gd

    - name: Install node
      run: |
        echo "Install NVM"
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
        if [ -s "$HOME/.nvm/nvm.sh" ]; then \. "$HOME/.nvm/nvm.sh"; fi
        echo "Install node"
        nvm install ${{ matrix.node }}
        nvm use ${{ matrix.node }}

    - uses: actions/checkout@v1

    - name: Install php-scoper
      run: |
        composer global require humbug/php-scoper@0.11.4 --prefer-dist --no-interaction --no-progress
        mkdir -p tools
        ln -sf $HOME/.composer/vendor/bin/php-scoper tools/php-scoper

    - name: Install composer dependencies
      run: composer install --prefer-dist --no-interaction --no-progress

    - name: Run php-scoper
      run: ./tools/php-scoper add-prefix

    - name: Remove composer dev dependencies
      run: composer update --no-dev --optimize-autoloader --prefer-dist --no-interaction --no-progress

    - name: Run npm install
      run: |
        if [ -s "$HOME/.nvm/nvm.sh" ]; then \. "$HOME/.nvm/nvm.sh"; fi
        npm install

    - name: Run npm build
      run: |
        if [ -s "$HOME/.nvm/nvm.sh" ]; then \. "$HOME/.nvm/nvm.sh"; fi
        npm run build

    - name: Trim to production node_modules
      run: |
        rm -rf node_modules
        if [ -s "$HOME/.nvm/nvm.sh" ]; then \. "$HOME/.nvm/nvm.sh"; fi
        npm install --production --no-bin-links

    - name: Upload build result
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build

    - name: Upload languages
      uses: actions/upload-artifact@v1
      with:
        name: languages
        path: languages

    - name: Upload styles
      uses: actions/upload-artifact@v1
      with:
        name: css
        path: css

  test_singlesite:
    name: Test single site
    needs: build
    strategy:
      matrix:
        mysql:
        - '5.7'
        php:
        - '7.0'
        - '7.1'
        - '7.2'
        - '7.3'
        - '7.4'
        wordpress:
        - '5.0'
        - '5.1'
        - '5.2'
        - '5.3'
        - '5.4'
        - latest
        - trunk
    runs-on: ubuntu-latest
    container:
      image: php:${{ matrix.php }}
      volumes:
      - $GITHUB_WORKSPACE:/var/www/html
    services:
      mysql:
        image: mysql:${{ matrix.mysql }}
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306
        volumes:
        - $HOME/mysql:/var/lib/mysql
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: Set up container
      run: |
        echo "Install base packages"
        apt-get update
        apt-get install -y build-essential \
          libssl-dev \
          gnupg \
          libfreetype6-dev \
          libicu-dev \
          libjpeg62-turbo-dev \
          libmcrypt-dev \
          libonig-dev \
          libxml2-dev \
          vim \
          wget \
          unzip \
          git \
          subversion \
          default-mysql-client

        echo "Install PHP extensions"
        docker-php-ext-install -j$(nproc) iconv intl xml soap opcache pdo pdo_mysql mysqli mbstring gd

    - name: Install composer
      run: |
        curl -sS -L https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer

    - uses: actions/checkout@v1

    - name: Download build files
      uses: actions/download-artifact@v1
      with:
        name: build

    - name: Download languages
      uses: actions/download-artifact@v1
      with:
        name: languages

    - name: Download styles
      uses: actions/download-artifact@v1
      with:
        name: css

    - name: Install phpunit
      run: |
        composer global require phpunit/phpunit ^6 --prefer-dist --no-interaction --no-progress
        mkdir -p tools
        ln -sf $HOME/.composer/vendor/bin/phpunit tools/phpunit

    - name: Install WordPress Test Suite
      run: ./bin/install-wp-tests.sh wordpress_test root root mysql ${{ matrix.wordpress }}

    - name: Run phpunit
      run: ./tools/phpunit $GITHUB_WORKSPACE

  test_multisite:
    name: Test multisite
    needs: build
    strategy:
      matrix:
        mysql:
        - '5.7'
        php:
        - '7.0'
        - '7.1'
        - '7.2'
        - '7.3'
        - '7.4'
        wordpress:
        - '5.0'
        - '5.1'
        - '5.2'
        - '5.3'
        - '5.4'
        - latest
        - trunk
    runs-on: ubuntu-latest
    container:
      image: php:${{ matrix.php }}
      volumes:
      - $GITHUB_WORKSPACE:/var/www/html
    services:
      mysql:
        image: mysql:${{ matrix.mysql }}
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306
        volumes:
        - $HOME/mysql:/var/lib/mysql
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: Set up container
      run: |
        echo "Install base packages"
        apt-get update
        apt-get install -y build-essential \
          libssl-dev \
          gnupg \
          libfreetype6-dev \
          libicu-dev \
          libjpeg62-turbo-dev \
          libmcrypt-dev \
          libonig-dev \
          libxml2-dev \
          vim \
          wget \
          unzip \
          git \
          subversion \
          default-mysql-client

        echo "Install PHP extensions"
        docker-php-ext-install -j$(nproc) iconv intl xml soap opcache pdo pdo_mysql mysqli mbstring gd

    - name: Install composer
      run: |
        curl -sS -L https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer

    - uses: actions/checkout@v1

    - name: Download build files
      uses: actions/download-artifact@v1
      with:
        name: build

    - name: Download languages
      uses: actions/download-artifact@v1
      with:
        name: languages

    - name: Download styles
      uses: actions/download-artifact@v1
      with:
        name: css

    - name: Install phpunit
      run: |
        composer global require phpunit/phpunit ^5 --prefer-dist --no-interaction --no-progress
        mkdir -p tools
        ln -sf $HOME/.composer/vendor/bin/phpunit tools/phpunit

    - name: Install WordPress Test Suite
      run: ./bin/install-wp-tests.sh wordpress_test root root mysql ${{ matrix.wordpress }}

    - name: Run phpunit
      run: ./tools/phpunit -c phpunit-multisite.xml $GITHUB_WORKSPACE
