name: "🚀 RELEASE: To WordPress.org"
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          ini-values: "phar.readonly=0"
          tools: "composer:v1"
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-cache-

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install PHIVE
        run: |
          wget -O phive.phar "https://phar.io/releases/phive.phar"
          wget -O phive.phar.asc "https://phar.io/releases/phive.phar.asc"
          gpg --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79
          gpg --verify phive.phar.asc phive.phar
          rm phive.phar.asc
          chmod +x phive.phar
          mv phive.phar /usr/local/bin/phive
      - name: Install PHP Scoper
        run: phive install https://github.com/humbug/php-scoper/releases/download/0.13.9/php-scoper.phar --force-accept-unsigned
      - name: Install composer build dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      - name: Scope PHP files
        run: ./tools/php-scoper add-prefix
      - name: Install composer dependencies
        run: composer update --no-interaction --no-progress --no-suggest --no-dev --prefer-dist --optimize-autoloader

      - name: Install NPM build dependencies
        run: npm install --no-progress --no-audit
      - name: Run NPM build
        run: npm run build
      - name: Prune NPM packages for production
        run: npm prune --production

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: "a-z-listing"

